### ISSUE TITLE
During import of a ConcatV2 TensorFlow layer, constant layers are ignored

### ISSUE THREAD

**Issue by coder80** [opencv/opencv#12931]
System information (version)
- OpenCV =>  4.0.0 - pre :grey_question:
- Operating System / Platform =>  Ubuntu 16.04 :grey_question:
- Compiler => GCC :grey_question:

##### Detailed description

During import of a ConcatV2 TensorFlow layer, input constant layers are ignored
For example:

lambda_4/Variable is constant layer, but it is not found in the graph

```
node {
  name: "lambda_4/concatenate_2/concat"
  op: "ConcatV2"
  input: "max_pooling2d_2/MaxPool"
  input: "lambda_4/Variable"
  input: "lambda_4/concatenate_2/concat/axis"
  attr {
    key: "N"
    value {
      i: 2
    }
  }
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
}
```

##### Steps to reproduce

We can see that code (populateNet function in the tf_importer.cpp):

```
             for (int ii = from; ii < to; ii++)
            {
                Pin inp = parsePin(layer.input(ii));
                if (layer_id.find(inp.name) == layer_id.end())
                    CV_Error(Error::StsError, "Input layer not found: " + inp.name);
                connect(layer_id, dstNet, inp, id, ii - from);
            }
```

We are looking for it in the layer_id only, but all const layers place in the value_id.

**Comment by dkurt** [comment]
@coder80, Could you please clarify an origin of constant blob `lambda_4/Variable`? Please add some TenosrFlow code here to generate similar graph.

**Comment by coder80** [comment]
@dkurt,

Perhaps we can make that fix (?)

```
for (int ii = from; ii < to; ii++)
            {
                Pin inp = parsePin(layer.input(ii));
                if (layer_id.find(inp.name) == layer_id.end())
                    if (value_id.find(inp.name) == value_id.end())
                        CV_Error(Error::StsError, "Input layer not found: " + inp.name);
                connect(layer_id, dstNet, inp, id, ii - from);
            }
```

**Comment by dkurt** [comment]
@coder80, For now OpenCV doesn't support this kind of operation. Concat layer works only with variables. However you may replace `ConcatV2` node to `Pad` node. In example, 

```yaml
node {
  name: "paddings"
  op: "Const"
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 4
          }
          dim {
            size: 2
          }
        }
        int_val: 0
        int_val: 0
        int_val: 0
        int_val: 1
        int_val: 0
        int_val: 1
        int_val: 0
        int_val: 0
      }
    }
  }
}
node {
  name: "lambda_4/concatenate_2/concat"
  op: "Pad"
  input: "max_pooling2d_2/MaxPool"
  input: "paddings"
}
```
Note that you need to specify padding sizes (begins and ends) explicitly. If your model works with NHWC data, you'll need change last two `int_val` which corresponds to depth dimension.
