### ISSUE TITLE
assertion failed error in net.forward(). OpenCV 4.0.1-dev and Tensorflow

### ISSUE THREAD

**Issue by shelkesagar29** [opencv/opencv#13751]
##### System information (version)
- OpenCV => 4.0.1-dev
- Operating System / Platform => Ubuntu 16.04
-TensorFlow => 1.12.0
##### Detailed description
```
Traceback (most recent call last):
File "/home/harmanx/opencv_dnn_inference/inference.py", line 14, in <module>
    out = nn_2.forward()
cv2.error: OpenCV(4.0.1-dev) /home/harmanx/opencv/modules/dnn/src/dnn.cpp:2281: error: (-215:Assertion failed) inp.total() in function 'allocateLayers'
```

nn.forward() gives assertion failed error while using TensorFlow frozen graph for Inception_v1 neural network.
I have optimized and transformed graph before feeding to OpenCV dnn using following commands.
```
python3 ~/tensorflow/tensorflow/python/tools/freeze_graph.py \
  --input_graph=80ms_inception.pb \
  --input_binary=True \
  --input_checkpoint=checkpoints_80ms_inception/inception_80ms.ckpt. \
  --output_graph=frozen_graph.pb \
  --output_node_names=inception_v1/fully_connected/prob_output
```
```
python3 ~/tensorflow/tensorflow/python/tools/optimize_for_inference.py \
  --input frozen_graph.pb \
  --output optimized_frozen_graph.pb \
  --frozen_graph True \
  --input_names x,p \
  --output_names inception_v1/fully_connected/prob_output
```
```
~/tensorflow/bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
  --in_graph=optimized_frozen_graph.pb \
  --out_graph=transformed_frozen_graph.pb \
  --inputs='x','p' \
  --outputs='inception_v1/fully_connected/prob_output' \
  --transforms="fold_constants sort_by_execution_order"
```
##### Steps to reproduce

Python code I have used is as follows
```python
import cv2
import numpy as np

# Load frozen graph
nn_2 = cv2.dnn.readNetFromTensorflow("./transformed_frozen_graph.pb")

# Load test image
test_image = cv2.imread("./user01_fluorescent@3:117965879.png")
cv2.imshow("test_image", test_image)
cv2.waitKey(50)
test_image = cv2.resize(test_image, (224, 224))
blob = cv2.dnn.blobFromImage(test_image, 55.02, (224, 224), (13.05, 13.07, 12.79), False, crop=False)

nn_2.setInput(blob)
out = nn_2.forward()

# Get a class with a highest score.
out = out.flatten()
classId = np.argmax(out)
print(classId)
confidence = out[classId]
print(confidence)
```
NOTE* Inference using TensorFlow is working with the same graph.
.pb and .pbtxt files can be obtained here
https://drive.google.com/open?id=1WHix43VOs1aRqOMfERLQdcNrtjyAer4E

**Comment by dkurt** [comment]
Looks like your model is not fully turned to testing phase. There are `Dropout` nodes:
![screenshot from 2019-02-04 08-36-22](https://user-images.githubusercontent.com/25801568/52191899-fb9ac200-2857-11e9-97a7-9ba791f47a36.png)

Please try to get rid of them.

As an alternative solution, you may create a text graph instead modifying a binary one:
```python
import cv2 as cv

cv.dnn.writeTextGraph('transformed_frozen_graph.pb', 'graph.pbtxt')
```

Then open `graph.pbtxt` and remove the following nodes:

```yaml
node {
  name: "p"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
}
```
```yaml
  name: "inception_v1/fully_connected/dropout/Shape"
  name: "inception_v1/fully_connected/dropout/random_uniform/RandomUniform"
  name: "inception_v1/fully_connected/dropout/random_uniform/mul"
  name: "inception_v1/fully_connected/dropout/random_uniform"
  name: "inception_v1/fully_connected/dropout/add"
  name: "inception_v1/fully_connected/dropout/Floor"
  name: "inception_v1/fully_connected/dropout/div"
  name: "inception_v1/fully_connected/dropout/mul"
```

Modify input of subsequent MatMul:
```yaml
node {
  name: "inception_v1/fully_connected/MatMul_1"
  op: "MatMul"
  # input: "inception_v1/fully_connected/dropout/mul"
  input: "inception_v1/fully_connected/Relu"
  input: "w_fc_1"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "transpose_a"
    value {
      b: false
    }
  }
  attr {
    key: "transpose_b"
    value {
      b: false
    }
  }
}
```

Repeat the same steps for `dropout_1` and remove all the `Const` nodes at the beginning of the graph. Use resulting `graph.pbtxt` as a second argument of `readNetFromTensorFlow`.

Please close an issue if there is no problem with this approach.
