### ISSUE TITLE
Strange output size in last convolution DNN face detector

### ISSUE THREAD

**Issue by lubagov** [opencv/opencv#15106]
in this commit, 03850008b9901ebe177b8f12efc47657ceab4fc4 by some reason, was changed padding in last convolution. After this, convolutions, conv8_2_h, conv9_2_h has output blob size 5x5. But, last detection levels should be 3x3 and 1x1, like in original SSD. When it detect big face 100 pixels side or more, i get strange effect:

![Frame_screenshot_20 07 2019](https://user-images.githubusercontent.com/6134203/61582874-fc3ec080-ab38-11e9-8e79-c2d4d1194e93.png)

When i remove this padding, and set to 0, it fine working:
![Frame_screenshot_20 07 2019_](https://user-images.githubusercontent.com/6134203/61582875-fc3ec080-ab38-11e9-952d-f7b4224c4c04.png)

for what, was this commit made?

**Comment by dkurt** [comment]
1. Can you compare the model with and without padding with the same image (current issue description shows two different images)
2. There is a description of corresponding PR so you can understand the motivation: https://github.com/opencv/opencv/pull/10216

**Comment by lubagov** [comment]
I can see this description, but it is trange description.
Really, each level SSD should detect higher size image, if add this padding all 3 blocks dtect image with 300/5=60 pixels (for 300x300 input), because blob output size:

layer:  conv6_1_h shape: (1, 128, 19, 19)
layer:  conv6_2_h shape: (1, 256, 10, 10)
layer:  conv7_1_h shape: (1, 64, 10, 10)
layer:  conv7_2_h shape: (1, 128, 5, 5)
layer:  conv8_1_h shape: (1, 64, 5, 5)
**layer:  conv8_2_h shape: (1, 128, 5, 5)
layer:  conv9_1_h shape: (1, 64, 5, 5)
layer:  conv9_2_h shape: (1, 128, 5, 5)**

after i add this padding back, shape sizes is:

layer:  conv7_1_h shape: (1, 64, 10, 10)
layer:  conv7_2_h shape: (1, 128, 5, 5)
layer:  conv8_1_h shape: (1, 64, 5, 5)
**layer:  conv8_2_h shape: (1, 128, 3, 3)
layer:  conv9_1_h shape: (1, 64, 3, 3)
layer:  conv9_2_h shape: (1, 128, 1, 1)**

Next image, received from Caffe samples, without OpenCV:
![detect_result](https://user-images.githubusercontent.com/6134203/61583922-c8b76280-ab47-11e9-90da-67e8f697dc8e.jpg)
![detect_result](https://user-images.githubusercontent.com/6134203/61583926-ce14ad00-ab47-11e9-897f-c991136153da.jpg)

**Comment by dkurt** [comment]
Can you please add an origin sample to reproduce the problem? Am I right that 300x300 input blob resolution is used?

**Comment by lubagov** [comment]
Any image, it is not matter. Yes, 300 pixels, and face should be more then 60 pixels side.

**Comment by dkurt** [comment]
Cannot reproduce with the following image (face size: 102x191):
![face_sample](https://user-images.githubusercontent.com/25801568/61584057-509e6c00-ab4a-11e9-882f-dc0c677f0f15.jpg) ![out](https://user-images.githubusercontent.com/25801568/61584063-5e53f180-ab4a-11e9-939c-2c08e5a1609e.jpg)



command:
```
python3 ~/opencv/samples/dnn/object_detection.py opencv_fd --input face_sample.jpg --backend 3
```

**Comment by lubagov** [comment]
102x191 it is not 300x300

**Comment by lubagov** [comment]
python3 object_detection.py --input tstimg1.jpg --backend 3 --model ./face_detector/res10_300x300_ssd_iter_140000_fp16.caffemodel --config ./face_detector/deploy.prototxt

![tstimg1_withpad](https://user-images.githubusercontent.com/6134203/61584286-c48e4380-ab4d-11e9-884a-3e7ca2e248d5.jpg)
![tstimg1](https://user-images.githubusercontent.com/6134203/61584288-c8ba6100-ab4d-11e9-9ba4-6292ca82cac4.jpg)
![tstimg1_nopad](https://user-images.githubusercontent.com/6134203/61584303-0cad6600-ab4e-11e9-9999-7716c503dbf1.jpg)

**Comment by lubagov** [comment]
and yes i am sorry:

conv8_2_mbox_priorbox:
    min_size: 213.0
    max_size: 264.0

conv9_2_mbox_priorbox:
    min_size: 264.0
    max_size: 315.0

so, face should fit in this size to get effect.

**Comment by dkurt** [comment]
Can reproduce it now, thanks!

**Comment by dkurt** [comment]
@lubagov, Need you help to resolve this issue.

With `stride: 2` I could achieve both bug elimination and opportunity to run the model on lower resolution. Can you please check it on your data?

```yaml
layer {
  name: "conv8_2_h"
  type: "Convolution"
  bottom: "conv8_1_h"
  top: "conv8_2_h"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 128
    pad: 1
    kernel_size: 3
    stride: 2
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
// ...
layer {
  name: "conv9_2_h"
  type: "Convolution"
  bottom: "conv9_1_h"
  top: "conv9_2_h"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 128
    pad: 1
    kernel_size: 3
    stride: 2
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
```

Open question is if we need to apply it to both convolutions of just to first one.
