### ISSUE TITLE
Difference between Caffe and OpenCV prediction

### ISSUE THREAD

**Issue by paulbauriegel** [opencv/opencv#15133]
##### System information (version)
- OpenCV: `4.1.0-583-g199ddff13 (2019-07-19)`
- OS: `Ubuntu 18.04 64bit`
- Compiler: `gcc 8.3.0`

##### Detailed description
The output of the same Caffe model differs in Caffe and OpenCV. The output of caffe seems to be the correct one. It may have some correlation with the slice layer + Elementwise Max. Testing before (62) and everything is fine, but after the two layers the results are different (65).
I just a distance function to make the comparison of the matrices simple, but printing the numpy preview shows also different outcomes.

##### Steps to reproduce
- [prototxt](https://drive.google.com/open?id=1h-8z_U-Q1i0xHpEX8RvDVuYL6WaEcR8s)
- [caffemodel](https://drive.google.com/open?id=1Et3FnLrGIRFtOV1kCFLSdG79_hhVsz2I)

```python
import cv2
import caffe
import numpy as np

def hausdorff_dist(vol_a,vol_b):
     """Copied from https://stackoverflow.com/a/33824997"""
    dist_lst = []
    for idx in range(len(vol_a)):
        dist_min = 1000.0        
        for idx2 in range(len(vol_b)):
            dist= np.linalg.norm(vol_a[idx]-vol_b[idx2])
            if dist_min > dist:
                dist_min = dist
        dist_lst.append(dist_min)
    return np.max(dist_lst)

img1 = cv2.imread("some.jpg")
img1 = cv2.cvtColor(img1, cv2.COLOR_RGB2GRAY)
blob = cv2.dnn.blobFromImage(img1, 1., (128,128), True, crop=True)

model = cv2.dnn.readNetFromCaffe("model_lcnn_29v2.prototxt", "model_lcnn_29v2.caffemodel")
model.setInput(blob)
r = model.forward("65")

caffe.set_mode_cpu()
net = caffe.Net('model_lcnn_29v2.prototxt', "model_lcnn_29v2.caffemodel",caffe.TEST)
net.blobs['0'].data[...] = blob
c = net.forward(end='65')['65']

print(hausdorff_dist(r[0], c[0]))
```

**Comment by dkurt** [comment]
@paulbauriegel, Thanks for report!

Please try to replace
```yaml
layer {
  name: "63_64"
  type: "Slice"
  bottom: "62"
  top: "63"
  top: "64"
  slice_param {
    slice_point: 48
    slice_point: 96
    axis: 1
  }
}
```

onto
```yaml
layer {
  name: "63_64"
  type: "Slice"
  bottom: "62"
  top: "63"
  top: "64"
  slice_param {
    slice_point: 48
    axis: 1
  }
}
```
and check if it help to solve the problem.
