### ISSUE TITLE
pip install opencv takes 24 minutes on Python 3.9 on Travis CI

### ISSUE THREAD

**Issue by cclauss** [opencv/opencv#18692]
__.travis.yml__
```yaml
language: python
python: 3.9
install: pip install opencv-python  # This step takes 1,464 seconds
script: true
```
