### ISSUE TITLE
[security] Automated releases

### ISSUE THREAD

**Issue by gabibguti** [opencv/opencv#24332]
### Describe the feature and motivation

Automated releases can help keep your releases consistent, transparent for users and, save maintainance time. It also improves the security of the release by using a "trusted builder". A "trusted builder" provides a higher level of confidence, for example, that a `make` command always runs with the same flags.

### Additional context

To do that, one option is to create a GitHub workflow that runs when you create a new tag, then it builds, generates the necessary `.zip` and `.exe` files, generates the files SHA256, and creates the release on GitHub. Here's a quick draft on the idea:
```yml
# release.yml

on:
  push:
    tags:
      - '*'
...
  - name: build
    run: make build
  - name: generate sha256
    run: sha256sum output.zip
  - name: release
    uses: actions/create-release
    with:
      prerelease: false
      release_name: ${{ github.ref }}
      tag_name: ${{ github.ref }}
      body_path: ${{ body_with_sha_sums_and_link_to_changelog }}
  - name: upload release assets
    uses: actions/upload-release-asset
    with:
      asset_path: ./output.zip
```

About me, I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes.
