### ISSUE TITLE
RT-DETR: Multidimensional unsqueeze not implemented for ONNX

### ISSUE THREAD

**Issue by BigMuscle85** [opencv/opencv#26919]
### System Information

Platform: Ubuntu 22.04.5 LTS
Compiler: g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
OpenCV 4.12.0 compiled from git

### Detailed description

Ultralytics DNN framework supports training of RT-DETR network for object detection. This detector significantly outperforms their Yolo networks: https://docs.ultralytics.com/models/rtdetr/

However, when the trained model is exported to ONNX, OpenCV is not able to load it due to the following error:

```
[ERROR:0@0.087] global onnx_importer.cpp:1036 handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Unsqueeze]:(onnx_node!/model.23/decoder/layers.0/Unsqueeze) from domain='ai.onnx'
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.12.0-dev) /home/user/dnn/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1058: error: (-2:Unspecified error) in function 'handleNode'
> Node [Unsqueeze@ai.onnx]:(onnx_node!/model.23/decoder/layers.0/Unsqueeze) parse error: OpenCV(4.12.0-dev) /home/user/dnn/opencv/modules/dnn/src/onnx/onnx_importer.cpp:2282: error: (-213:The function/feature is not implemented) Multidimensional unsqueeze in function 'parseUnsqueeze'
```

### Steps to reproduce

Train any RT-DETR network using Ultralytics and export it to ONNX. Here is the example for Yolo11n network where Detect layer was replaced with RTDETRDecoder.

```
# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# Ultralytics YOLO11 object detection model with P3/8 - P5/32 outputs
# Model docs: https://docs.ultralytics.com/models/yolo11
# Task docs: https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolo11n.yaml' will call yolo11.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.50, 0.25, 1024] # summary: 319 layers, 2624080 parameters, 2624064 gradients, 6.6 GFLOPs
  s: [0.50, 0.50, 1024] # summary: 319 layers, 9458752 parameters, 9458736 gradients, 21.7 GFLOPs
  m: [0.50, 1.00, 512] # summary: 409 layers, 20114688 parameters, 20114672 gradients, 68.5 GFLOPs
  l: [1.00, 1.00, 512] # summary: 631 layers, 25372160 parameters, 25372144 gradients, 87.6 GFLOPs
  x: [1.00, 1.50, 512] # summary: 631 layers, 56966176 parameters, 56966160 gradients, 196.0 GFLOPs

# YOLO11n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 2, C3k2, [256, False, 0.25]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 2, C3k2, [512, False, 0.25]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 2, C3k2, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 2, C3k2, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9
  - [-1, 2, C2PSA, [1024]] # 10

# YOLO11n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 2, C3k2, [512, False]] # 13

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 2, C3k2, [256, False]] # 16 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 13], 1, Concat, [1]] # cat head P4
  - [-1, 2, C3k2, [512, False]] # 19 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 10], 1, Concat, [1]] # cat head P5
  - [-1, 2, C3k2, [1024, True]] # 22 (P5/32-large)

  - [[16, 19, 22], 1, RTDETRDecoder, [nc]] # Detect(P3, P4, P5)


```

```
from ultralytics import RTDETR

name = "yolo11n-rtdetr"

# Load a model
model = RTDETR(name + ".yaml")  # build a new model from YAML

# Train the model
results = model.train(name=name, data="yolo_dataset/dataset.yaml", imgsz=160, epochs=100, cache="disk", batch=32, mosaic=False, mixup=False)

# Export to ONN
model.export(format="onnx", simplify=True, optimize=True)
```

Load in C++:
```
dnn::Net net = dnn::readNetFromONNX(argv[1]);
Mat detection = net.forward();
```

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)
