### ISSUE TITLE
About net.getParam() function in dnn module

### ISSUE THREAD

**Issue by xinyaojiejie** [opencv/opencv#7279]
call of getParam() function as follows: 

cv::dnn::Net::LayerId LId("conv1_1");
dnn::Blob weights = net.getParam(LId, 0);

it will trigger an exception as follows:

Debug Assertion failed!

File f:\dd\vctools\crt\crtw32\misc\dbgdel.cpp
Expression: _BLOCK_TYPE_IS_VALID(pHead->nBlockUse)

**Comment by dkurtaev** [comment]
Tried network with single convolutional layer,
```YAML
name: "OurNet"
input: "data"
input_dim: 1
input_dim: 3
input_dim: 224
input_dim: 224

layer {
  name: "conv1_1"
  type: "Convolution"
  bottom: "data"
  top: "conv1_1"
  convolution_param {
    num_output: 4
    kernel_size: 3
    pad: 1
    stride: 1
  }
}
```
Received snapshot with weights using Caffe,
```
caffe train -solver ./solver.prototxt
```
where solver is
```YAML
max_iter: 0
snapshot_prefix: "./snapshot"
solver_mode: CPU
net: "./net.prototxt"
```
Building network using C++:
```c++
std::cout << "OpenCV version: " << CV_VERSION << std::endl;

cv::dnn::initModule();

cv::dnn::Net net = cv::dnn::readNetFromCaffe("./net.prototxt",
                                             "./snapshot_iter_0.caffemodel");

net.setBlob(".data", cv::dnn::Blob(cv::dnn::BlobShape(1, 3, 224, 224)));

net.allocate();

cv::dnn::Net::LayerId lid("conv1_1");
cv::dnn::Blob params = net.getParam(lid);
std::cout << params.shape() << std::endl;
```
Output:
```
OpenCV version: 3.1.0-dev

Net Outputs(1):
conv1_1
[4, 3, 3, 3]
```
:question: Might your forget pass snapshot with parameters? When I tried model prototxt only,
```c++
cv::dnn::Net net = cv::dnn::readNetFromCaffe("./net.prototxt");
```
parameters blobs are empty (I have not found internal definition of trainable parameters for layers)
:question: Without explicit input data blob setup not working too.
